Repository district0x/district-registry, pull requests merged in 2019-11, with the labels that each got.

#89 Small fixes to lein clean, and ui-only development
  dev/user.clj
  project.clj
Labels: could have

#90 Potential Fixes for Vote Input Button Issues
  dev/user.clj
  project.clj
  resources/public/index.html
  src/district_registry/ui/detail/page.cljs
Labels: bug

#97 Feature/circleci
  .circleci/config.yml
  .travis.yml
  README.md
  docker-push.sh
  migrations/check_ran_migrations.js
  migrations/utils.js
  project.clj
  src/district_registry/shared/smart_contracts_dev.cljs
  test/district_registry/tests/smart_contracts/utils.cljs
  truffle.js
Labels: draft
